(function(g){var window=this;var LBa=function(a,b,c,d){var e=b.ac();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.gd(c,d?d:"mqdefault.jpg");var k=b instanceof g.xO?g.YU(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.wQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.xO?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.sl||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Tl(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.yQ&&(c.playlist_length=b.getLength());a.update(c)},C5=function(a,b){g.DH.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.A=a;this.created=!1},D5=function(a){g.W.call(this,{I:"div",
N:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},P:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",P:[{I:"span",N:"ytp-upnext-header",ca:"Up Next"},{I:"span",N:"ytp-upnext-title",ca:"{{title}}"},{I:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},P:[{I:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",N:"ytp-svg-autoplay-circle",
U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",P:[{I:"span",N:"ytp-upnext-cancel"},{I:"span",N:"ytp-upnext-paused",ca:"Autoplay is paused"}]}]});this.D=null;
var b=this.o["ytp-upnext-cancel"];this.D=new g.W({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ca:"Cancel"});g.N(this,this.D);this.D.W("click",this.DR,this);this.D.wa(b);this.A=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.F=null;this.J=new g.gu(this.co,5E3,this);g.N(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.OT);this.bD();this.R(a,"autonavvisibility",this.bD);this.R(a,"mdxnowautoplaying",
this.cT);this.R(a,"mdxautoplaycanceled",this.dT);this.R(a,"mdxautoplayupnext",this.LF);3==this.A.Ra()&&(a=(a=g.eU(g.$T(this.A)))?a.AK():null)&&this.LF(a)},MBa=function(a,b){a.F=b;
LBa(a,b,g.Y(a.A),"hqdefault.jpg")},E5=function(a,b){if(!a.C){g.eG("a11y-announce","Up Next "+a.F.title);
a.K=g.pG();a.C=new g.gu((0,g.A)(a.Cr,a,b),25);a.Cr(b);var c=b||g.Y(a.A).experiments.A("autoplay_time")||1E4;a.A.xa("onAutonavCoundownStarted",c)}g.vq(a.element,"ytp-upnext-autoplay-paused")},G5=function(a){F5(a);
a.K=g.pG();a.Cr();g.T(a.element,"ytp-upnext-autoplay-paused")},F5=function(a){a.C&&(a.C.dispose(),a.C=null)},H5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.A);if(c.experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.F.ac(),a.co(),a.G=new window.Notification("Up Next",{body:d.title,icon:d.gd(c)}),a.H=a.R(a.G,"click",a.DT),a.J.start())}F5(a);a.A.Bk(!1,b)},NBa=function(a){C5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.C=new g.W({I:"div",N:"ytp-subscribe-card",P:[{I:"img",N:"ytp-author-image",U:{src:b.profilePicture}},{I:"div",N:"ytp-subscribe-card-right",P:[{I:"div",N:"ytp-author-name",ca:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.N(this,this.C);this.C.wa(this.element);this.D=new g.NZ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Lf,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.D);this.D.wa(this.C.o["html5-subscribe-button-container"]);this.hide()},I5=
function(a){var b=g.Y(a),c=g.MI||g.mf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",fa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",N:"ytp-videowall-still-image",U:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",P:[{I:"span",N:"ytp-videowall-still-info-bg",P:[{I:"span",N:"ytp-videowall-still-info-content",U:c,P:[{I:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",
N:"ytp-videowall-still-info-author",ca:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",ca:"Live"},{I:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",ca:"{{playlist_length}}"},")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
P:[{I:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.F=d;this.A=a;this.C=null;this.D=new g.NF(this);g.N(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.Y(a).Z&&(a=a.app.ia,b=this.element,g.Pa(a.o,b),g.Sa(a.o,b),c=String(a.H++),b.setAttribute("data-visual-id",c),g.ff(this,(0,g.A)(a.G,a,b)));this.G()},J5=function(a){C5.call(this,a,"videowall-endscreen");
this.M=a;this.H=0;this.D=[];this.J=this.G=this.F=null;this.K=this.T=!1;this.Y=new g.NF(this);g.N(this,this.Y);this.L=new g.gu(g.Fa(g.T,this.element,"ytp-show-tiles"),0);g.N(this,this.L);var b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},P:[g.TU()]});g.N(this,b);b.wa(this.element);b.W("click",this.zP,this);this.O=new g.xH({I:"div",N:"ytp-endscreen-content"});g.N(this,this.O);this.O.wa(this.element);b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":"Next"},P:[g.UU()]});g.N(this,b);b.wa(this.element);b.W("click",this.yP,this);this.C=new D5(a);g.N(this,this.C);g.zU(this.A,this.C.element,4);this.hide()},K5=function(a){return g.BU(a.A)&&a.fy()&&!a.J},OBa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.DX(b);
g.N(a,b);return b})},L5=function(a){var b=a.Ku();
b!=a.T&&(a.T=b,a.A.V("autonavvisibility"))},M5=function(a){g.GU.call(this,a);
this.A=null;this.B=new g.NF(this);g.N(this,this.B);this.C=g.Y(a);PBa(a)?this.A=new J5(this.o):this.C.Ga?this.A=new NBa(this.o):this.A=new C5(this.o);g.N(this,this.A);g.zU(this.o,this.A.element,4);this.wE();this.B.R(a,"videodatachange",this.wE,this);this.B.R(a,"crn_endscreen",this.yN,this);this.B.R(a,"crx_endscreen",this.zN,this)},PBa=function(a){a=g.Y(a);
return a.od&&!a.Ga};
g.t(C5,g.DH);C5.prototype.create=function(){this.created=!0};
C5.prototype.destroy=function(){this.created=!1};
C5.prototype.fy=function(){return!1};
C5.prototype.Ku=function(){return!1};g.t(D5,g.W);g.h=D5.prototype;g.h.co=function(){this.G&&(this.J.stop(),this.Ha(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.bD=function(){g.CH(this,g.aU(this.A))};
g.h.DT=function(){window.focus();this.co()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Cr=function(a){a=a||g.Y(this.A).experiments.A("autoplay_time")||1E4;var b=Math.min(g.pG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.A.Ra()?H5(this,!0):this.C&&this.C.start()};
g.h.OT=function(a){!g.Vd(this.D.element,g.BF(a))&&g.DW(a,this.A)&&H5(this)};
g.h.DR=function(){g.cU(this.A,!0)};
g.h.cT=function(a){this.A.Ra();this.show();E5(this,a)};
g.h.LF=function(a){this.A.Ra();this.F&&this.F.ac().videoId==a.ac().videoId||MBa(this,a)};
g.h.dT=function(){this.A.Ra();F5(this);this.hide()};
g.h.X=function(){F5(this);this.co();g.W.prototype.X.call(this)};g.t(NBa,C5);g.t(I5,g.W);I5.prototype.Sk=function(){g.EU(this.A,this.element);var a=this.C.ac().videoId,b=this.C.getPlaylistId();g.a0(this.A.app,a,this.C.Vd,b,void 0,void 0,void 0)};
I5.prototype.H=function(a){g.DW(a,this.A,this.F,this.C.Vd||void 0)&&this.Sk()};
I5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.GF(a)||(this.Sk(),g.FF(a))}};
I5.prototype.G=function(){var a=this.A.getVideoData(),b=g.Y(this.A);this.F=a.isDni?!1:b.o};g.t(J5,C5);g.h=J5.prototype;g.h.create=function(){C5.prototype.create.call(this);var a=this.A.getVideoData();a&&(this.F=OBa(this,a),this.G=a);this.Tg();this.Y.R(this.A,"appresize",this.Tg);this.Y.R(this.A,"onVideoAreaChange",this.Tg);this.Y.R(this.A,"videodatachange",this.AP);this.Y.R(this.A,"autonavchange",this.YB);this.Y.R(this.A,"autonavcancel",this.xP);this.Y.R(this.element,"transitionend",this.fV)};
g.h.destroy=function(){g.PF(this.Y);g.jf(this.D);this.D=[];this.F=null;C5.prototype.destroy.call(this);g.vq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.fy=function(){return 1!=this.G.autonavState};
g.h.show=function(){C5.prototype.show.call(this);g.vq(this.element,"ytp-show-tiles");g.Y(this.A).A?g.iu(this.L):this.L.start();(this.K||this.J&&this.J!=this.G.clientPlaybackNonce)&&g.cU(this.A,!1);K5(this)?(L5(this),2==this.G.autonavState?g.Y(this.A).experiments.o("fast_autonav_in_background")&&3==this.A.aj()?H5(this.C,!0):E5(this.C):3==this.G.autonavState&&G5(this.C)):(g.cU(this.A,!0),L5(this))};
g.h.hide=function(){C5.prototype.hide.call(this);G5(this.C);L5(this)};
g.h.fV=function(a){g.BF(a)==this.element&&this.Tg()};
g.h.Tg=function(){if(this.F&&this.F.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.rU(this.M,!0),b=g.RH(this.M);b&&(b=b.zd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.F.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,D=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&D)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(D)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.hd(a.width/m||1,1,1.21);n*=g.hd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Ph(a,m,n);g.wh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});MBa(this.C,this.F[0]);g.U(this.element,"ytp-endscreen-takeover",K5(this));L5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),p=g.id(p+this.H,l),0!=r){u=this.D[c];u||(u=new I5(this.A),this.D[c]=u,a.appendChild(u.element));D=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-D-4,S=Math.floor(m*(f+r)/b)-H-4;g.Dh(u.element,H,D);g.Ph(u.element,S,L);g.wh(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==r);g.U(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.F[p];r.C!=p&&(r.C=p,LBa(r,p,g.Y(r.A),g.tq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),u=(p=p.Vd)&&p.itct)&&(p=r.A,g.Y(p).Z&&(p=p.app.ia,r=r.element,D=r.getAttribute("data-visual-id"),g.Pa(p.o,r),g.CU(p,"onLogServerVeCreated",{id:D,tracking_params:u})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.D.length-1;b>=c;b--)e=this.D[b],g.Pd(e.element),g.hf(e);this.D.length=c}};
g.h.AP=function(){var a=this.A.getVideoData();this.G!=a&&(this.H=0,this.F=OBa(this,a),this.G=a,this.Tg())};
g.h.yP=function(){this.H+=this.D.length;this.Tg()};
g.h.zP=function(){this.H-=this.D.length;this.Tg()};
g.h.EM=function(){return!!this.C.C};
g.h.YB=function(a){1==a?(this.K=!1,this.J=this.G.clientPlaybackNonce,F5(this.C),this.B&&this.Tg()):(this.K=!0,this.B&&K5(this)&&(2==a?E5(this.C):3==a&&G5(this.C)))};
g.h.xP=function(a){if(a){for(a=0;a<this.D.length;a++)g.FU(this.M,this.D[a].element,!0);this.YB(1)}else this.J=null,this.K=!1;this.Tg()};
g.h.Ku=function(){return this.B&&K5(this)};g.t(M5,g.GU);g.h=M5.prototype;g.h.vB=function(){var a=this.o.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!PBa(this.o)||b;a=g.VO(a,"ypc_module");var c=g.D_(this.o.app);return b&&!a&&!c};
g.h.uB=function(){return this.A.Ku()};
g.h.AM=function(){return this.uB()?this.A.EM():!1};
g.h.X=function(){g.xU(this.o,"endscreen");g.GU.prototype.X.call(this)};
g.h.load=function(){g.GU.prototype.load.call(this);this.A.show()};
g.h.unload=function(){g.GU.prototype.unload.call(this);this.A.hide();this.A.destroy()};
g.h.yN=function(a){this.vB()&&(this.A.created||this.A.create(),"load"==a.getId()&&this.load())};
g.h.zN=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.wE=function(){g.xU(this.o,"endscreen");var a=Math.max(1E3*(this.o.getVideoData().lengthSeconds-10),0);a=new g.tQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.tQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.uU(this.o,[a,b])};g.xX.endscreen=M5;})(_yt_player);
